---
- name: Deploy Azure Bastion Host
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: "cc_ansible_test"
    location: "eastus" # Choose your desired Azure region
    vnet_name: "demo_vnet"
    vnet_address_prefix: "10.0.0.0/16"
    bastion_subnet_name: "AzureBastionSubnet"
    bastion_subnet_address_prefix: "10.0.2.0/24"
    public_ip_name: "rehl8PublicIP"
    bastion_host_name: "rehel8BastionHost"
    bastion_sku: "Standard"
    azure_subscription_id: "a6146403-3256-4e07-8d93-2574db310783"

  tasks:
    #- name: Create Azure Resource Group
    #  azure_rm_resourcegroup:
    #    name: "{{ resource_group_name }}"
    #    location: "{{ location }}"
    #    state: present

   # - name: Create Azure Virtual Network
   #   azure_rm_virtualnetwork:
   #     resource_group: "{{ resource_group_name }}"
   #     name: "{{ vnet_name }}"
   #     address_prefixes:
   #       - "{{ vnet_address_prefix }}"
   #     location: "{{ location }}"
   #     state: present

    - name: Create Azure Bastion Subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        virtual_network_name: "{{ vnet_name }}"
        name: "{{ bastion_subnet_name }}"
        address_prefix: "{{ bastion_subnet_address_prefix }}"
        state: present

    - name: Create Azure Public IP for Bastion
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        name: "{{ public_ip_name }}"
        location: "{{ location }}"
        allocation_method: Static
        sku: Standard # Bastion requires Standard SKU for Public IP
        state: present

    - name: Create Azure Bastion Host
      azure_rm_bastionhost:
        resource_group: "{{ resource_group_name }}"
        name: "{{ bastion_host_name }}"
        location: "{{ location }}"
        sku: "{{ bastion_sku }}"
        ip_configurations:
          - name: "ipconfig1"
            subnet:
              id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group_name }}/providers/Microsoft.Network/virtualNetworks/{{ vnet_name }}/subnets/{{ bastion_subnet_name }}"
            public_ip_address:
              id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group_name }}/providers/Microsoft.Network/publicIPAddresses/{{ public_ip_name }}"
        state: present
