---
- name: Create a new user with a hashed password
  hosts: your_target_hosts
  become: yes # Use become to run tasks with elevated privileges
  tasks:
    - name: Ensure the user 'newuser' exists with a hashed password
      ansible.builtin.user:
        name: localadmin
        password: "{{ 'Ansible12345' | password_hash('sha512') }}"
        state: present
        update_password: on_create # Only set the password when the user is created
        shell: /bin/bash # Optional: Set the user's default shell
        home: /home/newuser # Optional: Set the user's home directory

 
